interface TrabalhosProps {
  titulo: string
  ano: number
  tecnica: string
  dimensoes: string
  imagem: string
}

export const trabalhos: TrabalhosProps[] = [
  {
    titulo: 'Buquê com fita vermelha',
    ano: 2025,
    tecnica: 'Óleo sobre tela',
    dimensoes: '71,5 x 51,5 cm',
    imagem: '/imgs/BUQUECOMFITAVERMELHA.webp',
  },
  {
    titulo: 'Mesa de baralho cigano',
    ano: 2025,
    tecnica: 'Óleo sobre tela',
    dimensoes: '71,5 x 51,5 cm',
    imagem: '/imgs/MESADEBARALHOCIGANO.webp',
  },
  {
    titulo: 'Cesta de Frutas Amarelas',
    ano: 2025,
    tecnica: 'Óleo sobre tela',
    dimensoes: '70 x 50 cm',
    imagem: '/imgs/CESTADEFRUTASAMARELAS.webp',
  },
  {
    titulo: 'Cesta com frutas e pães',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/CESTACOMFRUTASEPAES.webp',
  },
  {
    titulo: 'Melão para Oxum IV',
    ano: 2024,
    tecnica: 'Óleo e pasta de cera sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/MELAOPARAOXUMIV.webp',
  },
  {
    titulo: 'Vamos defumar filhos de fé',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '22 x 16 cm',
    imagem: '/imgs/VAMOSDEFUMARFILHOSDEFE.webp',
  },
  {
    titulo: '"Eu vi um clarão na mata, Eu pensava que era dia"',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '40 x 50 cm',
    imagem: '/imgs/EUVIUMCLARAONASMATASEUPENSAVAQUEERADIA.webp',
  },
  {
    titulo: 'Risca fogo',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/RISCAFOGO.webp',
  },
  {
    titulo: 'Coleção de vasos',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '40 x 30 cm',
    imagem: '/imgs/COLECAODEVASOS.webp',
  },
  {
    titulo: 'Veio do mar de Janaína',
    ano: 2024,
    tecnica: 'Óleo e pasta de cera sobre tela',
    dimensoes: '50 x 40 cm',
    imagem: '/imgs/VEIODOMARDEJANAINA.webp',
  },
  {
    titulo: 'Vida, corpo e espírito',
    ano: 2024,
    tecnica: 'Óleo e pasta de cera sobre tela',
    dimensoes: '40 x 50 cm',
    imagem: '/imgs/VIDACORPOEESPIRITO.webp',
  },
  {
    titulo: 'Pito',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/PITO.webp',
  },
  {
    titulo: 'Moça',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/MOCA.webp',
  },
  {
    titulo: 'Deitada',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '60 x 80 cm',
    imagem: '/imgs/DEITADA.webp',
  },
  {
    titulo: 'Búzios',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '35 x 30 cm',
    imagem: '/imgs/BUZIOS.webp',
  },
  {
    titulo: 'Aurora',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '40 x 30 cm',
    imagem: '/imgs/AURORA.webp',
  },
  {
    titulo: 'Okê Arô',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '30 x 35 cm',
    imagem: '/imgs/OKEARO.webp',
  },
  {
    titulo: 'Odoyá',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '22 x 16 cm',
    imagem: '/imgs/ODOYA.webp',
  },
  {
    titulo: 'Quiabos na gamela',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/QUIABOSNAGAMELA.webp',
  },
  {
    titulo: 'Anestesia',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/ANESTESIA.webp',
  },
  {
    titulo: 'Florzinhas',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '22 x 16 cm',
    imagem: '/imgs/FLORZINHAS.jpg',
  },
  {
    titulo: 'Acarajés para Iansã (e para os Eguns)',
    ano: 2024,
    tecnica: 'Óleo sobre tela',
    dimensoes: '40 x 50 cm',
    imagem: '/imgs/ACARAJESPARAIANSA.jpg',
  },

  {
    titulo: 'Quem tem fé tem tudo, quem não tem fé não tem nada',
    ano: 2023,
    tecnica: 'Encáustica sobre MDF',
    dimensoes: '40 x 30 cm',
    imagem: '/imgs/QUEMTEMFETEMTUDOQUEMNAOTEMFENAOTEMNADA.jpg',
  },
  {
    titulo: 'Melão para Oxum III',
    ano: 2023,
    tecnica: 'Óleo sobre MDF',
    dimensoes: '19 x 24 cm',
    imagem: '/imgs/MELAOPARAOXUM3.jpg',
  },
  {
    titulo: 'Lança de Ouro',
    ano: 2023,
    tecnica: 'Óleo e folha dourada sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/LANCADEOURO.jpg',
  },
  {
    titulo: 'Encanto',
    ano: 2023,
    tecnica: 'Óleo e folha dourada sobre tela',
    dimensoes: '16 x 22 cm',
    imagem: '/imgs/ENCANTO.jpg',
  },

  {
    titulo: 'Oferenda para Oxum',
    ano: 2019,
    tecnica: 'Óleo e pasta de cera sobre tela',
    dimensoes: '20 x 40 cm',
    imagem: '/imgs/OFERENDAPARAOXUM.jpg',
  },
  {
    titulo: 'Orayêyêô',
    ano: 2019,
    tecnica: 'Encáustica sobre MDF',
    dimensoes: '24 x 19 cm',
    imagem: '/imgs/ORAYEYEO.jpg',
  },
]
